packages:
  - 'client'
  - 'backend'

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  core-js: set this to true or false
  esbuild: true
  prisma: true
  unrs-resolver: set this to true or false
