import { ATTENDANCE_STATUS } from './attendanceTypes.js';

/**
 * Shared status colors for schedule dots, workflow icons, and operations board lanes.
 * All dot and icon colors are kept in one palette (SCHEDULE_WORKFLOW_COLORS).
 * WORKFLOW_STATUS_COLORS is a thin uppercase-keyed view of the same palette.
 */
export const SCHEDULE_WORKFLOW_STATUS = {
  NOT_TAKEN: 'not_taken',
  DRAFT: 'draft',
  TAKEN: 'taken',
  SUBMITTED: 'submitted',
  UNDER_REVIEW: 'under_review',
  UNDER_ADMIN_REVIEW: 'under_admin_review',
  UNDER_HR_REVIEW: 'under_hr_review',
  APPROVED: 'approved',
  ADMIN_APPROVED: 'admin_approved',
  REJECTED: 'rejected',
  AMENDED: 'amended',
};

export const SCHEDULE_WORKFLOW_COLORS = {
  [SCHEDULE_WORKFLOW_STATUS.NOT_TAKEN]: '#9ca3af',
  [SCHEDULE_WORKFLOW_STATUS.DRAFT]: '#9ca3af',
  [SCHEDULE_WORKFLOW_STATUS.TAKEN]: '#ca8a04',
  [SCHEDULE_WORKFLOW_STATUS.SUBMITTED]: '#3b82f6',
  [SCHEDULE_WORKFLOW_STATUS.UNDER_REVIEW]: '#7c3aed',
  [SCHEDULE_WORKFLOW_STATUS.UNDER_ADMIN_REVIEW]: '#A67B5B',
  [SCHEDULE_WORKFLOW_STATUS.UNDER_HR_REVIEW]: '#7c3aed',
  [SCHEDULE_WORKFLOW_STATUS.APPROVED]: '#166534',
  [SCHEDULE_WORKFLOW_STATUS.REJECTED]: '#ef4444',
  [SCHEDULE_WORKFLOW_STATUS.AMENDED]: '#ef4444',
};

export const WORKFLOW_STATUS_COLORS = {
  DRAFT: SCHEDULE_WORKFLOW_COLORS[SCHEDULE_WORKFLOW_STATUS.DRAFT],
  TAKEN: SCHEDULE_WORKFLOW_COLORS[SCHEDULE_WORKFLOW_STATUS.TAKEN],
  SUBMITTED: SCHEDULE_WORKFLOW_COLORS[SCHEDULE_WORKFLOW_STATUS.SUBMITTED],
  UNDER_REVIEW: SCHEDULE_WORKFLOW_COLORS[SCHEDULE_WORKFLOW_STATUS.UNDER_REVIEW],
  UNDER_ADMIN_REVIEW: SCHEDULE_WORKFLOW_COLORS[SCHEDULE_WORKFLOW_STATUS.UNDER_ADMIN_REVIEW],
  UNDER_HR_REVIEW: SCHEDULE_WORKFLOW_COLORS[SCHEDULE_WORKFLOW_STATUS.UNDER_HR_REVIEW],
  APPROVED: SCHEDULE_WORKFLOW_COLORS[SCHEDULE_WORKFLOW_STATUS.APPROVED],
  ADMIN_APPROVED: SCHEDULE_WORKFLOW_COLORS[SCHEDULE_WORKFLOW_STATUS.APPROVED],
  REJECTED: SCHEDULE_WORKFLOW_COLORS[SCHEDULE_WORKFLOW_STATUS.REJECTED],
  AMENDED: SCHEDULE_WORKFLOW_COLORS[SCHEDULE_WORKFLOW_STATUS.AMENDED],
};

export const WORKFLOW_STATUS_BADGE_COLORS = Object.fromEntries(
  Object.entries(WORKFLOW_STATUS_COLORS).map(([key, color]) => [key, { bg: color, text: '#ffffff', border: color }]),
);

export function getWorkflowBadgeColor(status) {
  return WORKFLOW_STATUS_BADGE_COLORS[status] || { bg: '#6b7280', text: '#ffffff', border: '#6b7280' };
}

/** Sky blue for participation indicators on the operations board */
export const BOARD_PARTICIPATION_COLOR = '#38bdf8';

/** Orange for comment indicators on the operations board */
export const BOARD_COMMENT_COLOR = '#f97316';

export const ATTENDANCE_BOARD_COLORS = {
  NOT_TAKEN: SCHEDULE_WORKFLOW_COLORS[SCHEDULE_WORKFLOW_STATUS.NOT_TAKEN],
  PRESENT: '#10b981',
  LATE: '#f59e0b',
  ABSENT: '#ef4444',
  EXCUSED: '#ec4899',
  HUMAN_CASE: '#8b5cf6',
};

export const SCHEDULE_WORKFLOW_STATUS_MAP = {
  NOT_TAKEN: SCHEDULE_WORKFLOW_STATUS.NOT_TAKEN,
  DRAFT: SCHEDULE_WORKFLOW_STATUS.DRAFT,
  TAKEN: SCHEDULE_WORKFLOW_STATUS.TAKEN,
  SUBMITTED: SCHEDULE_WORKFLOW_STATUS.SUBMITTED,
  UNDER_REVIEW: SCHEDULE_WORKFLOW_STATUS.UNDER_REVIEW,
  UNDER_ADMIN_REVIEW: SCHEDULE_WORKFLOW_STATUS.UNDER_ADMIN_REVIEW,
  UNDER_HR_REVIEW: SCHEDULE_WORKFLOW_STATUS.UNDER_HR_REVIEW,
  APPROVED: SCHEDULE_WORKFLOW_STATUS.APPROVED,
  ADMIN_APPROVED: SCHEDULE_WORKFLOW_STATUS.APPROVED,
  REJECTED: SCHEDULE_WORKFLOW_STATUS.REJECTED,
  AMENDED: SCHEDULE_WORKFLOW_STATUS.AMENDED,
};

export function resolveScheduleWorkflowKey(status) {
  if (!status) return SCHEDULE_WORKFLOW_STATUS.NOT_TAKEN;
  const ws = status.workflowStatus;
  if (ws && SCHEDULE_WORKFLOW_STATUS_MAP[ws]) {
    return SCHEDULE_WORKFLOW_STATUS_MAP[ws];
  }
  if (status.hasAttendance) {
    return SCHEDULE_WORKFLOW_STATUS.TAKEN;
  }
  return SCHEDULE_WORKFLOW_STATUS.NOT_TAKEN;
}

export function getScheduleWorkflowColor(status) {
  const key = resolveScheduleWorkflowKey(status);
  return SCHEDULE_WORKFLOW_COLORS[key];
}

export function getWorkflowStatusColor(statusId) {
  return WORKFLOW_STATUS_COLORS[statusId] || '#6b7280';
}

export function getAttendanceBoardColor(laneId) {
  return ATTENDANCE_BOARD_COLORS[laneId] || '#6b7280';
}

export function mapAttendanceTypeToBoardColor(status) {
  const map = {
    [ATTENDANCE_STATUS.PRESENT]: ATTENDANCE_BOARD_COLORS.PRESENT,
    [ATTENDANCE_STATUS.LATE]: ATTENDANCE_BOARD_COLORS.LATE,
    [ATTENDANCE_STATUS.ABSENT_NO_EXCUSE]: ATTENDANCE_BOARD_COLORS.ABSENT,
    [ATTENDANCE_STATUS.EXCUSED_LEAVE]: ATTENDANCE_BOARD_COLORS.EXCUSED,
    [ATTENDANCE_STATUS.HUMAN_CASE]: ATTENDANCE_BOARD_COLORS.HUMAN_CASE,
  };
  return map[status] || ATTENDANCE_BOARD_COLORS.NOT_TAKEN;
}
