export default {
  index: 'مركز المساعدة',
  '-- البدء': { type: 'separator', title: 'البدء' },
  home: 'الرئيسية',
  dashboard: 'لوحة التحكم',
  analytics: 'التحليلات',
  '-- الأكاديمي': { type: 'separator', title: 'الأكاديمي' },
  quizzes: 'الاختبارات',
  scheduling: 'الجدولة',
  '-- العمليات': { type: 'separator', title: 'العمليات' },
  attendance: 'الحضور',
  workflow: 'سير العمل',
  '-- التواصل': { type: 'separator', title: 'التواصل' },
  chat: 'الدردشة',
  notifications: 'الإشعارات',
  '-- الملفات': { type: 'separator', title: 'الملفات' },
  'smart-drive': 'القرص الذكي',
  '-- الحساب': { type: 'separator', title: 'الحساب' },
  profile: 'الملف الشخصي والإعدادات',
  '-- مرجع': { type: 'separator', title: 'مرجع' },
  glossary: 'مسرد المصطلحات',
  shortcuts: 'اختصارات لوحة المفاتيح',
  faq: 'الأسئلة الشائعة',
  changelog: 'ما الجديد',
}
