import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LangContext = createContext({
  lang: 'en',
  isRTL: false,
  setLang: () => {},
  toggleLang: () => {},
  t: (key) => key,
});

const DICT = {
  en: {
    admin_dashboard: 'Admin Dashboard',
    manage_platform: 'Manage your learning platform',
    activities: 'Activities',
    announcements: 'Announcements',
    users: 'Users',
    allowlist: 'Allowlist',
    classes: 'Classes',
    enrollments: 'Enrollments',
    submissions: 'Submissions',
    resources: 'Resources',
    announcements_management: 'Announcements Management',
    all: 'All',
    today: 'Today',
    last7: 'Last 7 Days',
    last30: 'Last 30 Days',
    // Forms and actions
    create: 'Create',
    creating: 'Creating...',
    update: 'Update',
    updating: 'Updating...',
    delete: 'Delete',
    deleting: 'Deleting...',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving...',
    edit: 'Edit',
    confirm_delete: 'Confirm Delete',
    are_you_sure: 'Are you sure you want to delete this item?',
    cannot_be_undone: 'This action cannot be undone.',
    // Class management
    classes_management: 'Classes Management',
    class_name: 'Class Name',
    class_code: 'Class Code',
    term: 'Term',
    select_owner: 'Select Owner (Admin)',
    create_class: 'Create Class',
    existing_classes: 'Existing Classes',
    fall: 'Fall',
    spring: 'Spring',
    summer: 'Summer',
    // Resources
    resources_management: 'Resources Management',
    resource_title: 'Resource Title',
    resource_description: 'Resource Description',
    resource_url: 'Resource URL',
    optional_resource: 'Optional Resource (not required for completion)',
    create_resource: 'Create Resource',
    // Users
    users_management: 'Users Management',
    email: 'Email',
    display_name: 'Display Name',
    role: 'Role',
    student: 'Student',
    admin: 'Admin',
    add_user: 'Add User',
    // Allowlist
    allowlist_management: 'Allowlist Management',
    student_emails: 'Student Emails (registration access)',
    admin_emails: 'Admin Emails (dashboard access)',
    admins_get_privileges: 'Admins get dashboard privileges',
    students_can_register: 'Students on this list can register',
    add: 'Add',
    import_multiple: 'Import Multiple',
    select_all: 'Select All',
    // Enrollments
    enrollments_management: 'Enrollments Management',
    select_user: 'Select User',
    // select_class defined once under enrollments; reuse the same key
    add_enrollment: 'Add Enrollment',
    current_enrollments: 'Current Enrollments',
    // Submissions
    submissions_management: 'Submissions Management',
    student_submissions: 'Student Submissions',
    // Activities
    activities_management: 'Activities Management',
    activity_title: 'Activity Title',
    activity_url: 'Activity URL',
    due_date: 'Due Date',
    pick_due_date: 'Pick due date & time',
    // Common
    loading: 'Loading...',
    loading_resources: 'Loading resources...',
    loading_leaderboard: 'Loading leaderboard...',
    loading_student_progress: 'Loading student progress...',
    search: 'Search',
    search_students: 'Search students...',
    student_progress_overview: 'Student Progress Overview',
    monitor_student_progress: 'Monitor all student progress and performance',
    total_students: 'Total Students',
    total_completions: 'Total Completions',
    average_score: 'Average Score',
    student_details: 'Student Details',
    total_score: 'Total Score',
    avg_score: 'Avg Score',
    last_activity: 'Last Activity',
    never: 'Never',
    no_students_found: 'No students found',
    no_students_match: 'No students match your search criteria.',
    detailed_progress: 'Detailed Progress',
    status: 'Status',
    score: 'Score',
    completed_at: 'Completed At',
    notes: 'Notes',
    activities_completed: 'Activities Completed',
    resources_completed: 'Resources Completed',
    total_activities: 'Total Activities',
    total_resources: 'Total Resources',
    resource_id: 'Resource ID',
    open: 'Open',
    auth_required: 'Authentication Required',
    login_to_view_resources: 'Please log in to view learning resources.',
    learning_resources: 'Learning Resources',
    resources_subtitle: 'Track your progress through supplementary learning materials',
    all_resources: 'All Resources',
    bookmarked: 'Bookmarked',
    no_resources_found: 'No resources found',
    no_resources_match: 'No resources match the current filter.',
    due: 'Due',
    completed_check: '✅ Completed',
    mark_complete: '⭕ Mark Complete',
    completed_only_admin_can_reopen: 'Completed. Only admin can reopen.',
    add_bookmark: 'Add bookmark',
    
    pending_clock: '⏳ Pending',
    completed: 'Completed',
    pending: 'Pending',
    featured: 'Featured',
    type: 'Type',
    level: 'Level',
    all_types: 'All Types',
    all_levels: 'All Levels',
    progress_summary: 'Progress Summary',
    required_remaining: 'Required Remaining',
    // Forms
    title_en: 'Title (English)',
    title_ar: 'Title (Arabic)',
    description_en: 'Description (English)',
    description_ar: 'Description (Arabic)',
    image_url: 'Image URL',
    max_score: 'Max Score',
    activity_url_label: 'Activity URL',
    activity_id: 'Activity ID',
    
    show_to_students: 'Show to students',
    allow_retakes: 'Allow retakes',
    send_email_to_students: 'Send email to students',
    create_announcement: 'Create announcement',
    language: 'Language',
    
    position: 'Position',
    // Notifications UI
    notifications: 'Notifications',
    mark_all_read: 'Mark all read',
    no_notifications_yet: 'No notifications yet',
    clear_all: 'Clear all',
    nothing_yet: 'Nothing yet!',
    confirm: 'Confirm',
    are_you_sure_clear_all: 'Are you sure you want to delete all notifications? This cannot be undone.',
    
    // Profile modal
    edit_profile: 'Edit Profile',
    no_deadline: 'No deadline',
    required: 'Required',
    optional: 'Optional',
    // SmartGrid & Buttons
    export_csv: 'Export CSV',
    view_details: 'View Details',
    close: 'Close',
    actions: 'Actions',
    no_data: 'No data available',
    registered_users: 'Registered Users',
    recent_announcements: 'Recent Announcements',
    student_progress: 'Progress',
    course: 'Course',
    visible: 'Visible',
    yes: 'Yes',
    no: 'No',
    enrolled: 'enrolled',
    year: 'Year',
    search_classes: 'Search classes by name or code...',
    students: 'Students',
    owner: 'Owner',
    code: 'Code',
    name: 'Name',
    created: 'Created',
    target: 'Target',
    title: 'Title',
    content: 'Content',
    enrolled_classes: 'Enrolled Classes',
    joined: 'Joined',
    files: 'Files',
    submitted_at: 'Submitted At',
    user: 'User',
    // Courses & Types (already defined above)
    training: 'Training',
    homework: 'Homework',
    quiz: 'Quiz',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    // Form labels (already defined above)
    title_english: 'Title (English)',
    title_arabic: 'Title (Arabic)',
    description_english: 'Description (English)',
    description_arabic: 'Description (Arabic)',
    create_activity: 'Create Activity',
    update_activity: 'Update Activity',
    existing_activities: 'Existing Activities',
    assignments_due_date: 'Assignment Due Date',
    send_email_notification: 'Send email notification',
    progress: 'Progress',
    // Navigation
    dashboard: 'Dashboard',
    see_how_you_rank: 'See how you rank among your peers',
    my_classes: 'Classes',
    direct_messages: 'Direct Messages',
    select_class: 'Select Class',
    instructor: 'Instructor',
    contact: 'Contact',
    // Activity Details
    due_date_label: 'Due Date',
    retakes_allowed: 'Retakes Allowed',
    total_questions: 'Total Questions',
    mark_as_complete: 'Mark as Complete',
    start_activity: 'Start Activity',
    // Chat
    global_chat: 'Global Chat',
    class_chat: 'Class Chat',
    type_message: 'Type your message...',
    send: 'Send',
    record_voice: 'Record Voice',
    stop_recording: 'Stop Recording',
    no_messages: 'No messages yet. Start the conversation!',
    no_conversations: 'No conversations',
    open_chat: 'Chat',
    view_activities: 'Activities',
    search_users: 'Search users by email or name',
    search_activities: 'Search activities',
    search_resources: 'Search resources',
    search_enrollments: 'Search enrollments',
    search_announcements: 'Search announcements',
    search_submissions: 'Search submissions by activity or student',
    search_by_email_name_ua: 'Search by email, name, or UA',
    announcement_content_english: 'Announcement Content (English)',
    announcement_content_arabic: 'Announcement Content (Arabic) - المحتوى بالعربية',
    class_name_arabic: 'Class Name (Arabic)',
    user_display_name_placeholder: 'Display Name (optional)',
    allowlist_email_placeholder: 'email@example.com',
    // SMTP page
    smtp_host: 'SMTP Host',
    smtp_port: 'SMTP Port',
    email_address: 'Email Address',
    app_password: 'App Password',
    sender_name: 'Sender Name',
    test_email: 'Test Email',
    save_configuration: 'Save Configuration',
    setup_instructions: 'Setup Instructions',
    // Tabs and sections
    smtp: 'SMTP',
    newsletter: 'Newsletter',
    activity_tab: 'Activity',
    categories_tab: 'Categories',
    email_management: 'Templates',
    email_logs: 'Email Logs',
    current_enrollments_title: 'Current Enrollments',
    learning_resources_title: 'Learning Resources',
    // Grid headers / labels
    id_col: 'ID',
    title_en_col: 'Title (EN)',
    title_col: 'Title',
    course_col: 'Course',
    type_col: 'Type',
    difficulty_col: 'Difficulty',
    assignment_due_date_col: 'Assignment Due Date',
    no_deadline_set: 'No deadline set',
    content_col: 'Content',
    target_col: 'Target',
    all_users_label: 'All Users',
    created_col: 'Created',
    unknown: 'Unknown',
    user_col: 'User',
    class_col: 'Class',
    role_col: 'Role',
    enrolled_col: 'Enrolled',
    activity_col: 'Activity',
    student_col: 'Student',
    status_col: 'Status',
    score_col: 'Score',
    submitted_at_col: 'Submitted At',
    files_col: 'Files',
    description_col: 'Description',
    due_date_col: 'Due Date',
    required_col: 'Required',
    actions_col: 'Actions',
    enrolled_classes_col: 'Enrolled Classes',
    display_name_col: 'Display Name',
    email_col: 'Email',
    no_files: 'No files',
    no_description: 'No description',
    required_yes: '✅ Required',
    required_optional: '⭕ Optional',
    // Buttons
    create_announcement_btn: 'Create Announcement',
    update_announcement_btn: 'Update Announcement',
    adding: 'Adding...',
    updating_generic: 'Updating...',
    add_user_btn: 'Add User',
    update_user_btn: 'Update User',
    invite_users_blurb: 'Invite users: Add an email to the allowlist below. The user must sign up with that email to appear in users and be linkable to enrollments, chats, and progress. We no longer create user docs without a UID.',
    auto_add_allowlist: 'Auto-add email to student allowlist',
    real_name_placeholder: 'Real Name (First Last)',
    student_number_placeholder: 'Student Number (Optional)',
    categories: 'Categories',
    general_no_class: 'General (no class)',
    graded: 'Graded',
    not_graded: 'Not Graded',
    late: 'Late',
    retake: 'Retake',
    retake_allowed: 'Retake Allowed',
    grading_status: 'Grading Status',
    completion: 'Completion',
    graded_on: 'Graded On',
    activity_breakdown: 'Activity Breakdown by Type',
    view_activity: 'View Activity',
    points: 'Points',
    points_to_next_rank: 'points to',
    recent_medals: 'Recent Medals Earned',
    no_medals_yet: 'No medals earned yet. Keep up the good work!',
    just_now: 'Just now',
    minutes_ago: 'minutes ago',
    hours_ago: 'hours ago',
    days_ago: 'days ago',
    your_progress: 'Your Progress',
    award_medals: 'Award Medals',
    select_students: 'Select Students',
    choose_medal: 'Choose Medal',
    reason_optional: 'Reason (Optional)',
    award_medals_btn: 'Award Medals',
    medals_awarded_success: 'Medals awarded successfully!',
    select_at_least_one_student: 'Please select at least one student',
    select_medal: 'Please select a medal',
    you_are_about_to_award: 'You are about to award',
    no_students_enrolled: 'No students enrolled in this class',
    enter_reason: 'Enter reason for awarding this medal...',
    awarding: 'Awarding...',
    class_story: 'Class Story',
    military_rank: 'Military Rank',
    you: 'You',
    rank_upgraded: 'RANK UPGRADED!',
    congratulations_promotion: 'Congratulations on your promotion!',
    continue: 'Continue',
    rank_history: 'Rank History',
    no_rank_history: 'No Rank History Yet',
    earn_points_to_rank_up: 'Earn points to start your military career!',
    first_rank: 'Starting Rank',
    promoted_from: 'Promoted from',
    ready_to_start: 'Ready to start',
    time_running: 'Time running...',
    paused: 'Paused',
    time_up: 'Time\'s up!',
    start: 'Start',
    pause: 'Pause',
    resume: 'Resume',
    reset: 'Reset',
    ready_to_track: 'Ready to track time',
    tracking_time: 'Tracking time...',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    impersonating: 'Impersonating',
    stop_impersonation: 'Stop Impersonation',
    viewing_as_student: 'Viewing as Student',
    impersonate_student: 'View as Student',
    impersonation_started: 'Now viewing as student',
    view_as: 'View',
    profile_settings: 'Profile & Settings',
    admins: 'Admins',
    teaching_assistant: 'Teaching Assistant',
    user_agent: 'User Agent',
    user_agent_col: 'User Agent',
    no_student_submissions: 'No student submissions available',
    all_status: 'All Status',
    search_by_email_subject: 'Search by email, subject',
    view_all_sent_emails: 'View all sent emails with full audit trail. Search by recipient, subject, or type',
    send_bulk_emails: 'Send bulk emails and view recent email logs',
    view_btn: 'View',
    sent: 'Sent',
    subject: 'Subject',
    when: 'When',
    to: 'To',
    date_time: 'Date/Time',
    from: 'From',
    template_id: 'Template ID',
    variables_used: 'Variables Used',
    email_preview: 'Email Preview',
    email_log_preview: 'Email Log Preview',
    manage_categories: 'Manage content categories (Programming, Computing, Algorithm, General). These drive the Activity dropdown and Home page tabs',
    name_arabic: 'Name (Arabic)',
    name_english: 'Name (English)',
    id_eg_python: 'ID (e.g., python)',
    order: 'Order',
    name_ar: 'Name (AR)',
    name_en: 'Name (EN)',
    id: 'ID',
    video: 'Video',
    link: 'Link',
    document: 'Document',
    all_users: 'All Users',
    newsletter: 'Newsletter',
    send_bulk_emails_view: 'Send bulk emails and view recent email logs',
    no_email_logs_yet: 'No email logs yet. Use the email composer to send a newsletter.',
    sent_status: 'Sent',
    failed_status: 'Failed',
    export_csv_btn: 'Export CSV',
    no_categories_yet: 'No categories yet. Click below to add defaults:',
    add_default_categories: 'Add Default Categories',
    // Progress page messages
    no_progress_yet: 'No progress yet',
    start_completing: 'Start completing activities to see your progress here',
    // Generic column/label keys
    activity: 'Activity',
    class: 'Class',
    description: 'Description',
    votes: 'Votes',
    // Profile modal
    real_name: 'Real Name',
    student_number: 'Student Number',
    phone_number: 'Phone Number',
    message_color: 'Message Bubble Color',
    preview: 'Preview',
    // Chat
    messages: 'messages',
    members: 'members',
    message_info: 'Message Info',
    attach: 'Attach',
    jump_to_bottom: 'Jump to bottom',
    // Dashboard buttons
    configure_email_smtp: 'Configure Email (SMTP)',
    login_activity: 'Login Activity',
    all_users: 'All Users',
    // Users actions
    set_password: 'Set Password',
    // Activity Logs
    activity_logs: 'Activity Logs',
    all_activity_types: 'All Activity Types',
    no_activity_logs_yet: 'No activity logs yet.',
    refresh: 'Refresh',
    // Email composer
    compose_email: 'Compose Email',
    sign_out: 'Sign Out',
    required_label: 'Required',
    // Notifications page
    search_notifications: 'Search notifications...',
    filter: 'Filter',
    unread: 'Unread',
    read: 'Read',
    sort_by: 'Sort by',
    newest_first: 'Newest First',
    oldest_first: 'Oldest First',
    no_results: 'No results found',
    try_different_search: 'Try a different search term',
    notifications_appear_here: 'Your notifications will appear here',
    notification: 'Notification',
    mark_as_read: 'Mark as read',
    // Profile page
    manage_your_profile: 'Manage your profile and preferences',
    personal_information: 'Personal Information',
    email_cannot_be_changed: 'Email address cannot be changed',
    display_name_placeholder: 'Enter your display name',
    phone_number_placeholder: 'Enter your phone number',
    appearance: 'Appearance',
    sample_message: 'This is how your messages will look',
    click_to_switch: 'Click to switch',
    profile_updated: 'Profile updated successfully',
    error_loading_profile: 'Error loading profile',
    error_updating_profile: 'Error updating profile',
    // HR and Attendance
    hr: 'HR',
    hr_attendance: 'HR Attendance',
    leave: 'Leave',
    leave_reason: 'Leave Reason',
    medical: 'Medical',
    official: 'Official',
    other: 'Other',
    manual_override: 'Manual Override',
    add_manual_attendance: 'Add Manual Attendance',
    override_attendance: 'Override Attendance',
    select_student: 'Select Student',
    attendance_note: 'Note',
    attendance_reason: 'Reason',
    actor: 'Actor',
    overridden_by: 'Overridden By',
    // Student Profile
    student_profile: 'Student Profile',
    attendance_summary: 'Attendance Summary',
    performance_summary: 'Performance Summary',
    total_sessions: 'Total Sessions',
    present_count: 'Present',
    absent_count: 'Absent',
    late_count: 'Late',
    leave_count: 'Leave',
    attendance_rate: 'Attendance Rate',
    homework_performance: 'Homework Performance',
    quiz_performance: 'Quiz Performance',
    activity_performance: 'Activity Performance',
    average_grade: 'Average Grade',
    completed_count: 'Completed',
    pending_count: 'Pending',
    // Role Access Management
    role_access: 'Role Access',
    manage_role_screens: 'Manage Role Screens',
    enable_disable_screens: 'Enable/Disable Screens per Role',
    screen_name: 'Screen Name',
    enabled: 'Enabled',
    disabled: 'Disabled',
    save_role_access: 'Save Role Access',
    role_access_updated: 'Role access updated successfully',
  },
  ar: {
    admin_dashboard: 'لوحة تحكم المشرف',
    manage_platform: 'إدارة منصة التعلم',
    activities: 'الأنشطة',
    announcements: 'الإعلانات',
    users: 'المستخدمون',
    allowlist: 'قائمة السماح',
    classes: 'الصفوف',
    enrollments: 'التسجيلات',
    submissions: 'التسليمات',
    announcements_management: 'إدارة الإعلانات',
    all: 'الكل',
    today: 'اليوم',
    last7: 'آخر 7 أيام',
    last30: 'آخر 30 يومًا',
    // Forms and actions
    create: 'إنشاء',
    creating: 'جاري الإنشاء...',
    update: 'تحديث',
    updating: 'جاري التحديث...',
    delete: 'حذف',
    deleting: 'جاري الحذف...',
    cancel: 'إلغاء',
    save: 'حفظ',
    saving: 'جاري الحفظ...',
    edit: 'تعديل',
    confirm_delete: 'تأكيد الحذف',
    are_you_sure: 'هل أنت متأكد من حذف هذا العنصر؟',
    cannot_be_undone: 'لا يمكن التراجع عن هذا الإجراء.',
    // Class management
    classes_management: 'إدارة الصفوف',
    class_name: 'اسم الصف',
    class_code: 'رمز الصف',
    term: 'الفصل الدراسي',
    select_owner: 'اختر المالك (مشرف)',
    // Activity Logs
    activity_logs: 'سجلات النشاط',
    all_activity_types: 'جميع أنواع الأنشطة',
    no_activity_logs_yet: 'لا توجد سجلات نشاط بعد.',
    refresh: 'تحديث',
    create_class: 'إنشاء صف',
    existing_classes: 'الصفوف الموجودة',
    fall: 'خريف',
    spring: 'ربيع',
    summer: 'صيف',
    // Resources
    resources_management: 'إدارة الموارد',
    resource_title: 'عنوان المورد',
    resource_description: 'وصف المورد',
    resource_url: 'رابط المورد',
    optional_resource: 'مورد اختياري (غير مطلوب للإكمال)',
    create_resource: 'إنشاء مورد',
    // Users
    users_management: 'إدارة المستخدمين',
    email: 'البريد الإلكتروني',
    display_name: 'الاسم المعروض',
    role: 'الدور',
    student: 'طالب',
    admin: 'مشرف',
    add_user: 'إضافة مستخدم',
    // Allowlist
    allowlist_management: 'إدارة قائمة السماح',
    student_emails: 'بريد الطلاب (وصول التسجيل)',
    admin_emails: 'بريد المشرفين (وصول لوحة التحكم)',
    admins_get_privileges: 'المشرفون يحصلون على صلاحيات لوحة التحكم',
    students_can_register: 'الطلاب في هذه القائمة يمكنهم التسجيل',
    add: 'إضافة',
    import_multiple: 'استيراد متعدد',
    // Enrollments
    enrollments_management: 'إدارة التسجيلات',
    select_user: 'اختر مستخدم',
    select_class: 'اختر صف',
    add_enrollment: 'إضافة تسجيل',
    current_enrollments: 'التسجيلات الحالية',
    // Activities
    activities_management: 'إدارة الأنشطة',
    activity_title: 'عنوان النشاط',
    activity_url: 'رابط النشاط',
    due_date: 'تاريخ الاستحقاق',
    pick_due_date: 'اختر التاريخ والوقت',
    // Common
    loading: 'جاري التحميل...',
    loading_resources: 'جاري تحميل الموارد...',
    loading_leaderboard: 'جاري تحميل لوحة المتصدرين...',
    loading_student_progress: 'جاري تحميل تقدم الطلاب...',
    search: 'بحث',
    search_students: 'ابحث عن الطلاب...',
    student_progress_overview: 'نظرة عامة على تقدم الطلاب',
    monitor_student_progress: 'راقب تقدم وأداء جميع الطلاب',
    total_students: 'إجمالي الطلاب',
    total_completions: 'إجمالي الإكمالات',
    average_score: 'متوسط الدرجة',
    student_details: 'تفاصيل الطلاب',
    student: 'الطالب',
    total_score: 'إجمالي الدرجة',
    avg_score: 'متوسط الدرجة',
    last_activity: 'آخر نشاط',
    never: 'أبدًا',
    no_students_found: 'لا يوجد طلاب',
    no_students_match: 'لا يوجد طلاب مطابقون لبحثك.',
    detailed_progress: 'تفاصيل التقدم',
    status: 'الحالة',
    score: 'الدرجة',
    completed_at: 'تاريخ الإكمال',
    notes: 'ملاحظات',
    activities_completed: 'الأنشطة المكتملة',
    resources_completed: 'الموارد المكتملة',
    total_activities: 'إجمالي الأنشطة',
    total_resources: 'إجمالي الموارد',
    resource_id: 'معرف المورد',
    open: 'فتح',
    auth_required: 'يتطلب تسجيل الدخول',
    login_to_view_resources: 'الرجاء تسجيل الدخول لعرض الموارد التعليمية.',
    learning_resources: 'الموارد التعليمية',
    resources_subtitle: 'تتبع تقدمك من خلال المواد التعليمية الإضافية',
    all_resources: 'كل الموارد',
    bookmarked: 'المفضلة',
    no_resources_found: 'لا توجد موارد',
    no_resources_match: 'لا توجد موارد مطابقة لعملية التصفية الحالية.',
    due: 'الموعد',
    completed_check: '✅ مكتمل',
    mark_complete: '⭕ وضع علامة مكتمل',
    completed_only_admin_can_reopen: 'مكتمل. فقط المشرف يمكنه إعادة فتحه.',
    add_bookmark: 'إضافة إلى المفضلة',
    remove_bookmark: 'إزالة',
    pending_clock: '⏳ قيد الانتظار',
    completed: 'مكتمل',
    pending: 'قيد الانتظار',
    featured: 'مميز',
    type: 'النوع',
    level: 'المستوى',
    all_types: 'كل الأنواع',
    all_levels: 'كل المستويات',
    progress_summary: 'ملخص التقدم',
    required_remaining: 'المطلوب المتبقي',
    // Forms
    title_en: 'العنوان (إنجليزي)',
    title_ar: 'العنوان (عربي)',
    description_en: 'الوصف (إنجليزي)',
    description_ar: 'الوصف (عربي)',
    image_url: 'رابط الصورة',
    max_score: 'الدرجة الكاملة',
    activity_url_label: 'رابط النشاط',
    activity_id: 'معرف النشاط',
    show_to_students: 'إظهار للطلاب',
    allow_retakes: 'السماح بالإعادة',
    send_email_to_students: 'إرسال بريد للطلاب',
    create_announcement: 'إنشاء إعلان',
    language: 'اللغة',
    update_activity: 'تحديث النشاط',
    create_activity: 'إنشاء نشاط',
    all_classes: 'كل الصفوف',
    all_terms: 'كل الفصول',
    // Notifications UI
    notifications: 'الإشعارات',
    mark_all_read: 'تحديد الكل كمقروء',
    no_notifications_yet: 'لا توجد إشعارات بعد',
    clear_all: 'حذف الكل',
    nothing_yet: 'لا شيء بعد!',
    confirm: 'تأكيد',
    are_you_sure_clear_all: 'هل أنت متأكد أنك تريد حذف كل الإشعارات؟ لا يمكن التراجع.',
    // Profile modal
    edit_profile: 'تعديل الملف الشخصي',
    no_deadline: 'لا يوجد موعد نهائي',
    required: 'مطلوب',
    optional: 'اختياري',
    // SmartGrid & Buttons
    export_csv: 'تصدير CSV',
    view_details: 'عرض التفاصيل',
    close: 'إغلاق',
    actions: 'إجراءات',
    no_data: 'لا توجد بيانات',
    recent_announcements: 'الإعلانات الأخيرة',
    student_progress: 'التقدم',
    course: 'المساق',
    visible: 'مرئي',
    yes: 'نعم',
    no: 'لا',
    enrolled: 'مسجل',
    year: 'السنة',
    search_classes: 'ابحث عن الصفوف بالاسم أو الرمز...',
    graded: 'مُقيّم',
    not_graded: 'غير مُقيّم',
    late: 'متأخر',
    retake: 'إعادة المحاولة',
    retake_allowed: 'إعادة المحاولة مسموح',
    grading_status: 'حالة التقييم',
    completion: 'الإكمال',
    graded_on: 'تم التقييم في',
    activity_breakdown: 'تفصيل الأنشطة حسب النوع',
    view_activity: 'عرض النشاط',
    points: 'النقاط',
    points_to_next_rank: 'نقطة إلى',
    recent_medals: 'الميداليات الأخيرة المكتسبة',
    no_medals_yet: 'لم يتم كسب أي ميداليات بعد. استمر في العمل الجيد!',
    just_now: 'الآن',
    minutes_ago: 'دقائق مضت',
    hours_ago: 'ساعات مضت',
    days_ago: 'أيام مضت',
    your_progress: 'تقدمك',
    award_medals: 'منح الميداليات',
    select_students: 'اختر الطلاب',
    select_all: 'تحديد الكل',
    choose_medal: 'اختر الميدالية',
    reason_optional: 'السبب (اختياري)',
    award_medals_btn: 'منح الميداليات',
    medals_awarded_success: 'تم منح الميداليات بنجاح!',
    select_at_least_one_student: 'الرجاء اختيار طالب واحد على الأقل',
    select_medal: 'الرجاء اختيار ميدالية',
    you_are_about_to_award: 'أنت على وشك منح',
    no_students_enrolled: 'لا يوجد طلاب مسجلين في هذا الصف',
    enter_reason: 'أدخل سبب منح هذه الميدالية...',
    awarding: 'جاري المنح...',
    class_story: 'قصة الصف',
    new_post: 'منشور جديد',
    write_post: 'اكتب منشوراً...',
    post_to_class: 'نشر في الصف',
    no_posts_yet: 'لا توجد منشورات بعد. كن أول من يشارك!',
    view_all_comments: 'عرض جميع التعليقات',
    write_comment: 'اكتب تعليقاً...',
    see_how_you_rank: 'شاهد ترتيبك بين أقرانك',
    your_position: 'موقعك',
    filter_by_class: 'تصفية حسب الصف',
    all_classes: 'جميع الصفوف',
    position: 'الموقع',
    military_rank: 'الرتبة العسكرية',
    you: 'أنت',
    export_csv: 'تصدير CSV',
    rank_upgraded: 'ترقية الرتبة!',
    congratulations_promotion: 'تهانينا على ترقيتك!',
    continue: 'متابعة',
    rank_history: 'تاريخ الرتب',
    no_rank_history: 'لا يوجد تاريخ رتب بعد',
    earn_points_to_rank_up: 'اكسب نقاطاً لبدء مسيرتك العسكرية!',
    first_rank: 'الرتبة الأولى',
    promoted_from: 'تمت الترقية من',
    ready_to_start: 'جاهز للبدء',
    time_running: 'الوقت يعمل...',
    paused: 'متوقف مؤقتاً',
    time_up: 'انتهى الوقت!',
    start: 'بدء',
    pause: 'إيقاف مؤقت',
    resume: 'استئناف',
    reset: 'إعادة تعيين',
    ready_to_track: 'جاهز لتتبع الوقت',
    tracking_time: 'تتبع الوقت...',
    hours: 'ساعات',
    minutes: 'دقائق',
    seconds: 'ثواني',
    impersonating: 'انتحال الشخصية',
    stop_impersonation: 'إيقاف الانتحال',
    viewing_as_student: 'العرض كطالب',
    impersonate_student: 'عرض كطالب',
    impersonation_started: 'الآن يتم العرض كطالب',
    view_as: 'عرض',
    profile_settings: 'الملف الشخصي والإعدادات',
    class_story: 'قصة الصف',
    owner: 'المالك',
    code: 'الرمز',
    name: 'الاسم',
    created: 'تاريخ الإنشاء',
    target: 'الهدف',
    title: 'العنوان',
    content: 'المحتوى',
    enrolled_classes: 'الصفوف المسجل بها',
    joined: 'تاريخ الانضمام',
    files: 'الملفات',
    submitted_at: 'تاريخ التسليم',
    user: 'المستخدم',
    // Courses & Types
    python: 'بايثون',
    computing: 'الحوسبة',
    training: 'تدريب',
    homework: 'واجب',
    quiz: 'اختبار',
    beginner: 'مبتدئ',
    intermediate: 'متوسط',
    advanced: 'متقدم',
    // Form labels
    activity_id: 'معرف النشاط',
    title_english: 'العنوان (إنجليزي)',
    title_arabic: 'العنوان (عربي)',
    description_english: 'الوصف (إنجليزي)',
    description_arabic: 'الوصف (عربي)',
    image_url: 'رابط الصورة',
    existing_activities: 'الأنشطة الموجودة',
    // enrollments_management defined above
    // users_management defined above
    // resources_management defined above
    student_submissions: 'تسليمات الطلاب',
    assignments_due_date: 'موعد تسليم الواجب',
    send_email_notification: 'إرسال إشعار بريد إلكتروني',
    // Allowlist & Permissions (duplicates removed)
    smtp_host_placeholder: 'smtp.gmail.com',
    class_code_placeholder: 'رمز الصف (اختياري)',
    resource_title_placeholder: 'عنوان المورد',
    resource_description_placeholder: 'وصف المورد (اختياري)',
    resource_url_placeholder: 'رابط المورد',
    user_email_placeholder: 'بريد المستخدم',
    // Tabs and sections
    smtp: 'SMTP',
    newsletter: 'النشرة البريدية',
    activity_tab: 'النشاط',
    categories: 'الفئات',
    categories_tab: 'الفئات',
    email_management: 'النماذج',
    email_logs: 'سجلات البريد',
    current_enrollments_title: 'التسجيلات الحالية',
    learning_resources_title: 'موارد التعلم',
    // Grid headers / labels
    id_col: 'المعرف',
    title_en_col: 'العنوان (إنجليزي)',
    title_col: 'العنوان',
    course_col: 'المقرر',
    type_col: 'النوع',
    difficulty_col: 'الصعوبة',
    assignment_due_date_col: 'موعد تسليم الواجب',
    no_deadline_set: 'لا يوجد موعد نهائي',
    content_col: 'المحتوى',
    target_col: 'الهدف',
    all_users_label: 'كل المستخدمين',
    created_col: 'تاريخ الإنشاء',
    unknown: 'غير معروف',
    user_col: 'المستخدم',
    class_col: 'الصف',
    role_col: 'الدور',
    enrolled_col: 'مسجل منذ',
    activity_col: 'النشاط',
    student_col: 'الطالب',
    status_col: 'الحالة',
    score_col: 'الدرجة',
    submitted_at_col: 'وقت التسليم',
    files_col: 'الملفات',
    description_col: 'الوصف',
    due_date_col: 'تاريخ الاستحقاق',
    required_col: 'إلزامي',
    actions_col: 'إجراءات',
    enrolled_classes_col: 'الصفوف المسجل بها',
    display_name_col: 'الاسم المعروض',
    email_col: 'البريد الإلكتروني',
    no_files: 'لا توجد ملفات',
    no_description: 'لا يوجد وصف',
    required_yes: '✅ إلزامي',
    required_optional: '⭕ اختياري',
    // Buttons
    create_announcement_btn: 'إنشاء إعلان',
    update_announcement_btn: 'تحديث الإعلان',
    adding: 'جاري الإضافة...',
    updating_generic: 'جاري التحديث...',
    add_user_btn: 'إضافة مستخدم',
    update_user_btn: 'تحديث المستخدم',
    invite_users_blurb: 'دعوة المستخدمين: أضف بريداً إلكترونياً إلى قائمة السماح أدناه. يجب أن يسجل المستخدم بهذا البريد ليظهر في قائمة المستخدمين ويصبح قابلاً للربط بالتسجيلات والمحادثات والتقدم. لم نعد ننشئ مستندات مستخدم بدون معرّف UID.',
    auto_add_allowlist: 'إضافة البريد تلقائياً إلى قائمة الطلاب المسموح لهم',
    real_name_placeholder: 'الاسم الحقيقي (الاسم الأول ثم الأخير)',
    student_number_placeholder: 'رقم الطالب (اختياري)',
    general_no_class: 'عام (بدون صف)',
    no_student_submissions: 'لا توجد تسليمات طلاب متاحة',
    all_status: 'كل الحالات',
    search_by_email_subject: 'ابحث بالبريد أو الموضوع',
    view_all_sent_emails: 'عرض جميع الرسائل المرسلة مع سجل التدقيق الكامل. ابحث حسب المستلم أو الموضوع أو النوع',
    send_bulk_emails: 'إرسال رسائل بريد إلكتروني جماعية وعرض سجلات البريد الأخيرة',
    
    view_btn: 'عرض',
    sent: 'مرسل',
    subject: 'الموضوع',
    when: 'متى',
    to: 'إلى',
    date_time: 'التاريخ/الوقت',
    
    
    from: 'من',
    template_id: 'معرف القالب',
    variables_used: 'المتغيرات المستخدمة',
    email_preview: 'معاينة البريد',
    email_log_preview: 'معاينة سجل البريد',
    manage_categories: 'إدارة فئات المحتوى (البرمجة، الحوسبة، الخوارزميات، عام). هذه تدير القائمة المنسدلة للنشاط وعلامات تبويب الصفحة الرئيسية',
    name_arabic: 'الاسم (عربي)',
    name_english: 'الاسم (إنجليزي)',
    id_eg_python: 'المعرف (مثال: python)',
    order: 'الترتيب',
    name_ar: 'الاسم (عربي)',
    name_en: 'الاسم (إنجليزي)',
    id: 'المعرف',
    
    
    
    
    
    video: 'فيديو',
    link: 'رابط',
    document: 'مستند',
    all_users: 'كل المستخدمين',
    teaching_assistant: 'مساعد تدريس',
    user_agent: 'وكيل المستخدم',
    user_agent_col: 'وكيل المستخدم',
    
    send_bulk_emails_view: 'إرسال رسائل بريد إلكتروني جماعية وعرض سجلات البريد الأخيرة',
    no_email_logs_yet: 'لا توجد سجلات بريد بعد. استخدم محرر البريد لإرسال نشرة بريدية.',
    sent_status: 'مرسل',
    failed_status: 'فشل',
    export_csv_btn: 'تصدير CSV',
    no_categories_yet: 'لا توجد فئات بعد. انقر أدناه لإضافة الافتراضيات:',
    add_default_categories: 'إضافة الفئات الافتراضية',
    // Navigation
    dashboard: 'لوحة التحكم',
    leaderboard: 'لوحة المتصدرين',
    chat: 'المحادثة',
    my_progress: 'تقدمي',
    my_classes: 'صفوفي',
    direct_messages: 'الرسائل المباشرة',
    instructor: 'المعلم',
    contact: 'تواصل',
    // Activity Details
    due_date_label: 'تاريخ الاستحقاق',
    retakes_allowed: 'إعادة المحاولة مسموح',
    total_questions: 'إجمالي الأسئلة',
    mark_as_complete: 'وضع علامة كمكتمل',
    start_activity: 'ابدأ النشاط',
    // Chat
    global_chat: 'المحادثة العامة',
    class_chat: 'محادثة الصف',
    type_message: 'اكتب رسالتك...',
    send: 'إرسال',
    record_voice: 'تسجيل صوتي',
    stop_recording: 'إيقاف التسجيل',
    no_messages: 'لا توجد رسائل حتى الآن. ابدأ المحادثة!',
    no_conversations: 'لا محادثات',
    open_chat: 'المحادثة',
    view_activities: 'الأنشطة',
    search_users: 'ابحث عن المستخدمين بالبريد أو الاسم',
    search_activities: 'ابحث عن الأنشطة',
    search_resources: 'ابحث عن الموارد',
    search_enrollments: 'ابحث في التسجيلات',
    search_announcements: 'ابحث في الإعلانات',
    // SMTP page
    smtp_host: 'مضيف SMTP',
    smtp_port: 'منفذ SMTP',
    email_address: 'عنوان البريد',
    app_password: 'كلمة مرور التطبيق',
    sender_name: 'اسم المرسل',
    test_email: 'اختبار البريد',
    save_configuration: 'حفظ الإعدادات',
    setup_instructions: 'تعليمات الإعداد',
    // Progress page messages
    no_progress_yet: 'لا يوجد تقدم بعد',
    start_completing: 'ابدأ بإكمال الأنشطة لعرض تقدمك هنا',
    // Chat poll
    create_poll: 'إنشاء استطلاع',
    add_option: 'إضافة خيار',
    question: 'السؤال',
    options: 'الخيارات',
    votes: 'أصوات',
    // Profile modal
    real_name: 'الاسم الحقيقي',
    student_number: 'رقم الطالب',
    phone_number: 'رقم الهاتف',
    message_color: 'لون فقاعة الرسالة',
    preview: 'معاينة',
    // Chat extras
    messages: 'رسائل',
    members: 'أعضاء',
    message_info: 'معلومات الرسالة',
    attach: 'إرفاق',
    jump_to_bottom: 'الانتقال للأسفل',
    // Dashboard buttons
    configure_email_smtp: 'إعداد البريد (SMTP)',
    login_activity: 'نشاط تسجيل الدخول',
    // Users actions
    set_password: 'تعيين كلمة المرور',
    // Email composer
    compose_email: 'إنشاء بريد',
    sign_out: 'تسجيل الخروج',
    required_label: 'إلزامي',
    // Notifications page
    search_notifications: 'البحث في الإشعارات...',
    filter: 'تصفية',
    unread: 'غير مقروء',
    read: 'مقروء',
    sort_by: 'ترتيب حسب',
    newest_first: 'الأحدث أولاً',
    oldest_first: 'الأقدم أولاً',
    no_results: 'لا توجد نتائج',
    try_different_search: 'جرب مصطلح بحث مختلف',
    notifications_appear_here: 'ستظهر إشعاراتك هنا',
    notification: 'إشعار',
    mark_as_read: 'وضع علامة كمقروء',
    // Profile page
    manage_your_profile: 'إدارة ملفك الشخصي وتفضيلاتك',
    personal_information: 'المعلومات الشخصية',
    email_cannot_be_changed: 'لا يمكن تغيير عنوان البريد الإلكتروني',
    display_name_placeholder: 'أدخل اسمك المعروض',
    phone_number_placeholder: 'أدخل رقم هاتفك',
    appearance: 'المظهر',
    sample_message: 'هكذا ستبدو رسائلك',
    click_to_switch: 'انقر للتبديل',
    profile_updated: 'تم تحديث الملف الشخصي بنجاح',
    error_loading_profile: 'خطأ في تحميل الملف الشخصي',
    error_updating_profile: 'خطأ في تحديث الملف الشخصي',
    // HR and Attendance
    hr: 'الموارد البشرية',
    hr_attendance: 'حضور الموارد البشرية',
    leave: 'إجازة',
    leave_reason: 'سبب الإجازة',
    medical: 'طبي',
    official: 'رسمي',
    other: 'أخرى',
    manual_override: 'تعديل يدوي',
    add_manual_attendance: 'إضافة حضور يدوي',
    override_attendance: 'تعديل الحضور',
    select_student: 'اختر طالب',
    attendance_note: 'ملاحظة',
    attendance_reason: 'السبب',
    actor: 'الفاعل',
    overridden_by: 'تم التعديل بواسطة',
    // Student Profile
    student_profile: 'ملف الطالب',
    attendance_summary: 'ملخص الحضور',
    performance_summary: 'ملخص الأداء',
    total_sessions: 'إجمالي الجلسات',
    present_count: 'حاضر',
    absent_count: 'غائب',
    late_count: 'متأخر',
    leave_count: 'إجازة',
    attendance_rate: 'معدل الحضور',
    homework_performance: 'أداء الواجبات',
    quiz_performance: 'أداء الاختبارات',
    activity_performance: 'أداء الأنشطة',
    average_grade: 'متوسط الدرجة',
    completed_count: 'مكتمل',
    pending_count: 'قيد الانتظار',
    // Role Access Management
    role_access: 'صلاحيات الأدوار',
    manage_role_screens: 'إدارة شاشات الأدوار',
    enable_disable_screens: 'تفعيل/تعطيل الشاشات لكل دور',
    screen_name: 'اسم الشاشة',
    enabled: 'مفعّل',
    disabled: 'معطّل',
    save_role_access: 'حفظ صلاحيات الأدوار',
    role_access_updated: 'تم تحديث صلاحيات الأدوار بنجاح',
  },
};

export const LangProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => localStorage.getItem('lang') || 'en');

  const setLang = (l) => {
    const value = l === 'ar' ? 'ar' : 'en';
    setLangState(value);
    localStorage.setItem('lang', value);
  };

  const toggleLang = () => setLang(lang === 'en' ? 'ar' : 'en');

  const isRTL = lang === 'ar';

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
  }, [lang, isRTL]);

  const t = useMemo(() => {
    const dict = DICT[lang] || DICT.en;
    return (key) => {
      const v = dict[key];
      if (v) return v;
      return String(key || '').replaceAll('_',' ');
    };
  }, [lang]);

  const value = useMemo(() => ({ lang, isRTL, setLang, toggleLang, t }), [lang, isRTL]);

  return (
    <LangContext.Provider value={value}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);

export { LangContext };
