export const ATTENDANCE_STATUS_CODES = {
  PRESENT: 'ATTENDANCE_PRESENT',
  ABSENT: 'ATTENDANCE_ABSENT',
  LATE: 'ATTENDANCE_LATE',
  LEAVE: 'ATTENDANCE_LEAVE',
  HUMAN_CASE: 'ATTENDANCE_HUMAN_CASE',
};

export const STANDUP_STATUS_CODES = {
  PRESENT: 'STANDUP_PRESENT',
  LATE: 'STANDUP_LATE',
  ABSENT: 'STANDUP_ABSENT',
  CLINIC: 'STANDUP_CLINIC',
};
