/**
 * Notification Constants - Canonical definitions
 * 
 * These are the single source of truth for notification events, categories,
 * priorities, and channels. Shared between backend and client.
 */

// Notification Categories (mapped to Prisma enum)
export const CATEGORIES = {
  SYSTEM: 'SYSTEM',
  ACADEMIC: 'ACADEMIC',
  ATTENDANCE: 'ATTENDANCE',
  ASSESSMENT: 'ASSESSMENT',
  COMMUNICATION: 'COMMUNICATION',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  WORKFLOW: 'WORKFLOW',
  FILE: 'FILE',
  QR: 'QR',
  BEHAVIOR: 'BEHAVIOR',
  PARTICIPATION: 'PARTICIPATION',
  PENALTY: 'PENALTY',
  RESOURCE: 'RESOURCE'
};

// Notification Events (canonical event names)
export const EVENTS = {
  // Workflow events
  WORKFLOW_SUBMITTED: 'workflow.submitted',
  WORKFLOW_ASSIGNED: 'workflow.assigned',
  WORKFLOW_APPROVED: 'workflow.approved',
  WORKFLOW_REJECTED: 'workflow.rejected',
  WORKFLOW_RETURNED: 'workflow.returned',
  WORKFLOW_RESUBMITTED: 'workflow.resubmitted',
  WORKFLOW_COMPLETED: 'workflow.completed',
  WORKFLOW_SLA_WARNING: 'workflow.sla_warning',
  WORKFLOW_SLA_OVERDUE: 'workflow.sla_overdue',
  WORKFLOW_AMENDED: 'workflow.amended',
  
  // Announcement events
  ANNOUNCEMENT_POSTED: 'announcement.posted',
  ANNOUNCEMENT_UPDATED: 'announcement.updated',
  ANNOUNCEMENT_DELETED: 'announcement.deleted',
  
  // QR events
  QR_CODE_SENT: 'qr.code_sent',
  QR_CODE_GENERATED: 'qr.code_generated',
  
  // Attendance events
  ATTENDANCE_MARKED: 'attendance.marked',
  ATTENDANCE_MARKED_PRESENT: 'attendance.marked_present',
  ATTENDANCE_MARKED_ABSENT: 'attendance.marked_absent',
  ATTENDANCE_MARKED_LATE: 'attendance.marked_late',
  ATTENDANCE_MARKED_EXCUSED: 'attendance.marked_excused',
  ATTENDANCE_THRESHOLD_WARNING: 'attendance.threshold_warning',
  ATTENDANCE_PATTERN_DETECTED: 'attendance.pattern_detected',
  
  // Behavior events
  BEHAVIOR_RECORDED: 'behavior.recorded',
  BEHAVIOR_POSITIVE_RECORDED: 'behavior.positive_recorded',
  BEHAVIOR_NEGATIVE_RECORDED: 'behavior.negative_recorded',
  BEHAVIOR_UPDATED: 'behavior.updated',
  BEHAVIOR_DELETED: 'behavior.deleted',
  
  // Participation events
  PARTICIPATION_RECORDED: 'participation.recorded',
  PARTICIPATION_EXPLAINED_LESSON: 'participation.explained_lesson',
  PARTICIPATION_GAVE_PROJECT: 'participation.gave_project',
  PARTICIPATION_GAVE_PAPER: 'participation.gave_paper',
  PARTICIPATION_GAVE_RESEARCH: 'participation.gave_research',
  PARTICIPATION_ACTIVE_DISCUSSION: 'participation.active_discussion',
  PARTICIPATION_ANSWERED_QUESTION: 'participation.answered_question',
  PARTICIPATION_HELPED_CLASSMATE: 'participation.helped_classmate',
  PARTICIPATION_EXCELLENT: 'participation.excellent',
  PARTICIPATION_UPDATED: 'participation.updated',
  PARTICIPATION_DELETED: 'participation.deleted',
  
  // Penalty events
  PENALTY_ASSIGNED: 'penalty.assigned',
  PENALTY_ASSIGNED_LATE: 'penalty.assigned_late',
  PENALTY_ASSIGNED_ABSENT: 'penalty.assigned_absent',
  PENALTY_ASSIGNED_MISCONDUCT: 'penalty.assigned_misconduct',
  PENALTY_UPDATED: 'penalty.updated',
  PENALTY_DELETED: 'penalty.deleted',
  PENALTY_WAIVED: 'penalty.waived',
  
  // File events
  FILE_SHARED: 'file.shared',
  FILE_UPLOADED: 'file.uploaded',
  FILE_DOWNLOADED: 'file.downloaded',
  FILE_DELETED: 'file.deleted',
  
  // Drive/Storage events
  DRIVE_FILE_SHARED: 'drive.file.shared',
  DRIVE_FOLDER_SHARED: 'drive.folder.shared',
  DRIVE_PERMISSION_REVOKED: 'drive.permission.revoked',
  DRIVE_FILE_UPLOADED: 'drive.file.uploaded',
  DRIVE_FOLDER_CREATED: 'drive.folder.created',
  DRIVE_FILE_DELETED: 'drive.file.deleted',
  DRIVE_FOLDER_DELETED: 'drive.folder.deleted',
  DRIVE_COMMENT_ADDED: 'drive.comment.added',
  
  // Resource events
  RESOURCE_ADDED: 'resource.added',
  RESOURCE_UPDATED: 'resource.updated',
  RESOURCE_DELETED: 'resource.deleted',
  RESOURCE_SHARED: 'resource.shared',
  
  // Enrollment events
  ENROLLMENT_CONFIRMED: 'enrollment.confirmed',
  ENROLLMENT_PENDING: 'enrollment.pending',
  ENROLLMENT_APPROVED: 'enrollment.approved',
  ENROLLMENT_REJECTED: 'enrollment.rejected',
  ENROLLMENT_DROPPED: 'enrollment.dropped',
  ENROLLMENT_COMPLETED: 'enrollment.completed',
  
  // Grade events
  GRADE_POSTED: 'grade.posted',
  GRADE_UPDATED: 'grade.updated',
  GRADE_CALCULATED: 'grade.calculated',
  GRADE_FINAL: 'grade.final',
  MARKS_UPDATED: 'marks.updated',
  REPEATED_ATTEMPT_GRADED: 'repeated_attempt.graded',
  
  // Quiz events
  QUIZ_AVAILABLE: 'quiz.available',
  QUIZ_STARTED: 'quiz.started',
  QUIZ_SUBMITTED: 'quiz.submitted',
  QUIZ_GRADED: 'quiz.graded',
  QUIZ_TIME_WARNING: 'quiz.time_warning',
  
  // Assignment events
  ASSIGNMENT_CREATED: 'assignment.created',
  ASSIGNMENT_DUE: 'assignment.due',
  ASSIGNMENT_DUE_SOON: 'assignment.due_soon',
  ASSIGNMENT_SUBMITTED: 'assignment.submitted',
  ASSIGNMENT_GRADED: 'assignment.graded',
  ASSIGNMENT_OVERDUE: 'assignment.overdue',
  
  // Activity events
  ACTIVITY_ASSIGNED: 'activity.assigned',
  ACTIVITY_COMPLETED: 'activity.completed',
  ACTIVITY_GRADED: 'activity.graded',
  ACTIVITY_FEEDBACK: 'activity.feedback',
  
  // System events
  SYSTEM_ALERT: 'system.alert',
  SYSTEM_MAINTENANCE: 'system.maintenance',
  SYSTEM_UPDATE: 'system.update',
  USER_ACCOUNT_CREATED: 'user.account_created',
  USER_PASSWORD_RESET: 'user.password_reset',
  USER_LOGIN: 'user.login'
};

// Notification Priorities (mapped to Prisma enum)
export const PRIORITIES = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

// Notification Channels
export const CHANNELS = {
  IN_APP: 'in_app',
  EMAIL: 'email',
  SMS: 'sms',
  PUSH: 'push'
};

// Delivery statuses
export const DELIVERY_STATUS = {
  QUEUED: 'queued',
  SENT: 'sent',
  DELIVERED: 'delivered',
  FAILED: 'failed',
  SKIPPED: 'skipped'
};

// Event to category mapping
export const EVENT_CATEGORIES = {
  // Workflow events
  [EVENTS.WORKFLOW_SUBMITTED]: CATEGORIES.WORKFLOW,
  [EVENTS.WORKFLOW_ASSIGNED]: CATEGORIES.WORKFLOW,
  [EVENTS.WORKFLOW_APPROVED]: CATEGORIES.WORKFLOW,
  [EVENTS.WORKFLOW_REJECTED]: CATEGORIES.WORKFLOW,
  [EVENTS.WORKFLOW_COMPLETED]: CATEGORIES.WORKFLOW,
  [EVENTS.WORKFLOW_SLA_WARNING]: CATEGORIES.WORKFLOW,
  [EVENTS.WORKFLOW_SLA_OVERDUE]: CATEGORIES.WORKFLOW,
  
  // Announcement events
  [EVENTS.ANNOUNCEMENT_POSTED]: CATEGORIES.ANNOUNCEMENT,
  [EVENTS.ANNOUNCEMENT_UPDATED]: CATEGORIES.ANNOUNCEMENT,
  [EVENTS.ANNOUNCEMENT_DELETED]: CATEGORIES.ANNOUNCEMENT,
  
  // QR events
  [EVENTS.QR_CODE_SENT]: CATEGORIES.QR,
  [EVENTS.QR_CODE_GENERATED]: CATEGORIES.QR,
  
  // Attendance events
  [EVENTS.ATTENDANCE_MARKED]: CATEGORIES.ATTENDANCE,
  [EVENTS.ATTENDANCE_MARKED_PRESENT]: CATEGORIES.ATTENDANCE,
  [EVENTS.ATTENDANCE_MARKED_ABSENT]: CATEGORIES.ATTENDANCE,
  [EVENTS.ATTENDANCE_MARKED_LATE]: CATEGORIES.ATTENDANCE,
  [EVENTS.ATTENDANCE_MARKED_EXCUSED]: CATEGORIES.ATTENDANCE,
  [EVENTS.ATTENDANCE_THRESHOLD_WARNING]: CATEGORIES.ATTENDANCE,
  [EVENTS.ATTENDANCE_PATTERN_DETECTED]: CATEGORIES.ATTENDANCE,
  
  // Behavior events
  [EVENTS.BEHAVIOR_RECORDED]: CATEGORIES.BEHAVIOR,
  [EVENTS.BEHAVIOR_POSITIVE_RECORDED]: CATEGORIES.BEHAVIOR,
  [EVENTS.BEHAVIOR_NEGATIVE_RECORDED]: CATEGORIES.BEHAVIOR,
  [EVENTS.BEHAVIOR_UPDATED]: CATEGORIES.BEHAVIOR,
  [EVENTS.BEHAVIOR_DELETED]: CATEGORIES.BEHAVIOR,
  
  // Participation events
  [EVENTS.PARTICIPATION_RECORDED]: CATEGORIES.PARTICIPATION,
  [EVENTS.PARTICIPATION_EXPLAINED_LESSON]: CATEGORIES.PARTICIPATION,
  [EVENTS.PARTICIPATION_GAVE_PROJECT]: CATEGORIES.PARTICIPATION,
  [EVENTS.PARTICIPATION_GAVE_PAPER]: CATEGORIES.PARTICIPATION,
  [EVENTS.PARTICIPATION_GAVE_RESEARCH]: CATEGORIES.PARTICIPATION,
  [EVENTS.PARTICIPATION_ACTIVE_DISCUSSION]: CATEGORIES.PARTICIPATION,
  [EVENTS.PARTICIPATION_ANSWERED_QUESTION]: CATEGORIES.PARTICIPATION,
  [EVENTS.PARTICIPATION_HELPED_CLASSMATE]: CATEGORIES.PARTICIPATION,
  [EVENTS.PARTICIPATION_EXCELLENT]: CATEGORIES.PARTICIPATION,
  [EVENTS.PARTICIPATION_UPDATED]: CATEGORIES.PARTICIPATION,
  [EVENTS.PARTICIPATION_DELETED]: CATEGORIES.PARTICIPATION,
  
  // Penalty events
  [EVENTS.PENALTY_ASSIGNED]: CATEGORIES.PENALTY,
  [EVENTS.PENALTY_ASSIGNED_LATE]: CATEGORIES.PENALTY,
  [EVENTS.PENALTY_ASSIGNED_ABSENT]: CATEGORIES.PENALTY,
  [EVENTS.PENALTY_ASSIGNED_MISCONDUCT]: CATEGORIES.PENALTY,
  [EVENTS.PENALTY_UPDATED]: CATEGORIES.PENALTY,
  [EVENTS.PENALTY_DELETED]: CATEGORIES.PENALTY,
  [EVENTS.PENALTY_WAIVED]: CATEGORIES.PENALTY,
  
  // File events
  [EVENTS.FILE_SHARED]: CATEGORIES.FILE,
  [EVENTS.FILE_UPLOADED]: CATEGORIES.FILE,
  [EVENTS.FILE_DOWNLOADED]: CATEGORIES.FILE,
  [EVENTS.FILE_DELETED]: CATEGORIES.FILE,
  
  // Drive/Storage events
  [EVENTS.DRIVE_FILE_SHARED]: CATEGORIES.FILE,
  [EVENTS.DRIVE_FOLDER_SHARED]: CATEGORIES.FILE,
  [EVENTS.DRIVE_PERMISSION_REVOKED]: CATEGORIES.FILE,
  [EVENTS.DRIVE_FILE_UPLOADED]: CATEGORIES.FILE,
  [EVENTS.DRIVE_FOLDER_CREATED]: CATEGORIES.FILE,
  [EVENTS.DRIVE_FILE_DELETED]: CATEGORIES.FILE,
  [EVENTS.DRIVE_FOLDER_DELETED]: CATEGORIES.FILE,
  [EVENTS.DRIVE_COMMENT_ADDED]: CATEGORIES.COMMUNICATION,
  
  // Resource events
  [EVENTS.RESOURCE_ADDED]: CATEGORIES.RESOURCE,
  [EVENTS.RESOURCE_UPDATED]: CATEGORIES.RESOURCE,
  [EVENTS.RESOURCE_DELETED]: CATEGORIES.RESOURCE,
  [EVENTS.RESOURCE_SHARED]: CATEGORIES.RESOURCE,
  
  // Enrollment events
  [EVENTS.ENROLLMENT_CONFIRMED]: CATEGORIES.ACADEMIC,
  [EVENTS.ENROLLMENT_PENDING]: CATEGORIES.ACADEMIC,
  [EVENTS.ENROLLMENT_APPROVED]: CATEGORIES.ACADEMIC,
  [EVENTS.ENROLLMENT_REJECTED]: CATEGORIES.ACADEMIC,
  [EVENTS.ENROLLMENT_DROPPED]: CATEGORIES.ACADEMIC,
  [EVENTS.ENROLLMENT_COMPLETED]: CATEGORIES.ACADEMIC,
  
  // Grade events
  [EVENTS.GRADE_POSTED]: CATEGORIES.ASSESSMENT,
  [EVENTS.GRADE_UPDATED]: CATEGORIES.ASSESSMENT,
  [EVENTS.GRADE_CALCULATED]: CATEGORIES.ASSESSMENT,
  [EVENTS.GRADE_FINAL]: CATEGORIES.ASSESSMENT,
  [EVENTS.MARKS_UPDATED]: CATEGORIES.ASSESSMENT,
  [EVENTS.REPEATED_ATTEMPT_GRADED]: CATEGORIES.ASSESSMENT,
  
  // Quiz events
  [EVENTS.QUIZ_AVAILABLE]: CATEGORIES.ASSESSMENT,
  [EVENTS.QUIZ_STARTED]: CATEGORIES.ASSESSMENT,
  [EVENTS.QUIZ_SUBMITTED]: CATEGORIES.ASSESSMENT,
  [EVENTS.QUIZ_GRADED]: CATEGORIES.ASSESSMENT,
  [EVENTS.QUIZ_TIME_WARNING]: CATEGORIES.ASSESSMENT,
  
  // Assignment events
  [EVENTS.ASSIGNMENT_CREATED]: CATEGORIES.ASSESSMENT,
  [EVENTS.ASSIGNMENT_DUE]: CATEGORIES.ASSESSMENT,
  [EVENTS.ASSIGNMENT_DUE_SOON]: CATEGORIES.ASSESSMENT,
  [EVENTS.ASSIGNMENT_SUBMITTED]: CATEGORIES.ASSESSMENT,
  [EVENTS.ASSIGNMENT_GRADED]: CATEGORIES.ASSESSMENT,
  [EVENTS.ASSIGNMENT_OVERDUE]: CATEGORIES.ASSESSMENT,
  
  // Activity events
  [EVENTS.ACTIVITY_ASSIGNED]: CATEGORIES.ASSESSMENT,
  [EVENTS.ACTIVITY_COMPLETED]: CATEGORIES.ASSESSMENT,
  [EVENTS.ACTIVITY_GRADED]: CATEGORIES.ASSESSMENT,
  [EVENTS.ACTIVITY_FEEDBACK]: CATEGORIES.ASSESSMENT,
  
  // System events
  [EVENTS.SYSTEM_ALERT]: CATEGORIES.SYSTEM,
  [EVENTS.SYSTEM_MAINTENANCE]: CATEGORIES.SYSTEM,
  [EVENTS.SYSTEM_UPDATE]: CATEGORIES.SYSTEM,
  [EVENTS.USER_ACCOUNT_CREATED]: CATEGORIES.SYSTEM,
  [EVENTS.USER_PASSWORD_RESET]: CATEGORIES.SYSTEM,
  [EVENTS.USER_LOGIN]: CATEGORIES.SYSTEM
};

// Default priority per event
export const EVENT_PRIORITIES = {
  // Workflow events
  [EVENTS.WORKFLOW_SUBMITTED]: PRIORITIES.NORMAL,
  [EVENTS.WORKFLOW_ASSIGNED]: PRIORITIES.NORMAL,
  [EVENTS.WORKFLOW_APPROVED]: PRIORITIES.NORMAL,
  [EVENTS.WORKFLOW_REJECTED]: PRIORITIES.HIGH,
  [EVENTS.WORKFLOW_COMPLETED]: PRIORITIES.NORMAL,
  [EVENTS.WORKFLOW_SLA_WARNING]: PRIORITIES.HIGH,
  [EVENTS.WORKFLOW_SLA_OVERDUE]: PRIORITIES.URGENT,
  
  // Announcement events
  [EVENTS.ANNOUNCEMENT_POSTED]: PRIORITIES.NORMAL,
  [EVENTS.ANNOUNCEMENT_UPDATED]: PRIORITIES.LOW,
  [EVENTS.ANNOUNCEMENT_DELETED]: PRIORITIES.LOW,
  
  // QR events
  [EVENTS.QR_CODE_SENT]: PRIORITIES.NORMAL,
  [EVENTS.QR_CODE_GENERATED]: PRIORITIES.NORMAL,
  
  // Attendance events
  [EVENTS.ATTENDANCE_MARKED]: PRIORITIES.LOW,
  [EVENTS.ATTENDANCE_MARKED_PRESENT]: PRIORITIES.LOW,
  [EVENTS.ATTENDANCE_MARKED_ABSENT]: PRIORITIES.HIGH,
  [EVENTS.ATTENDANCE_MARKED_LATE]: PRIORITIES.NORMAL,
  [EVENTS.ATTENDANCE_MARKED_EXCUSED]: PRIORITIES.LOW,
  [EVENTS.ATTENDANCE_THRESHOLD_WARNING]: PRIORITIES.HIGH,
  [EVENTS.ATTENDANCE_PATTERN_DETECTED]: PRIORITIES.HIGH,
  
  // Behavior events
  [EVENTS.BEHAVIOR_RECORDED]: PRIORITIES.NORMAL,
  [EVENTS.BEHAVIOR_POSITIVE_RECORDED]: PRIORITIES.NORMAL,
  [EVENTS.BEHAVIOR_NEGATIVE_RECORDED]: PRIORITIES.HIGH,
  [EVENTS.BEHAVIOR_UPDATED]: PRIORITIES.NORMAL,
  [EVENTS.BEHAVIOR_DELETED]: PRIORITIES.LOW,
  
  // Participation events
  [EVENTS.PARTICIPATION_RECORDED]: PRIORITIES.NORMAL,
  [EVENTS.PARTICIPATION_EXPLAINED_LESSON]: PRIORITIES.NORMAL,
  [EVENTS.PARTICIPATION_GAVE_PROJECT]: PRIORITIES.NORMAL,
  [EVENTS.PARTICIPATION_GAVE_PAPER]: PRIORITIES.NORMAL,
  [EVENTS.PARTICIPATION_GAVE_RESEARCH]: PRIORITIES.NORMAL,
  [EVENTS.PARTICIPATION_ACTIVE_DISCUSSION]: PRIORITIES.NORMAL,
  [EVENTS.PARTICIPATION_ANSWERED_QUESTION]: PRIORITIES.NORMAL,
  [EVENTS.PARTICIPATION_HELPED_CLASSMATE]: PRIORITIES.NORMAL,
  [EVENTS.PARTICIPATION_EXCELLENT]: PRIORITIES.NORMAL,
  [EVENTS.PARTICIPATION_UPDATED]: PRIORITIES.NORMAL,
  [EVENTS.PARTICIPATION_DELETED]: PRIORITIES.LOW,
  
  // Penalty events
  [EVENTS.PENALTY_ASSIGNED]: PRIORITIES.HIGH,
  [EVENTS.PENALTY_ASSIGNED_LATE]: PRIORITIES.HIGH,
  [EVENTS.PENALTY_ASSIGNED_ABSENT]: PRIORITIES.HIGH,
  [EVENTS.PENALTY_ASSIGNED_MISCONDUCT]: PRIORITIES.URGENT,
  [EVENTS.PENALTY_UPDATED]: PRIORITIES.NORMAL,
  [EVENTS.PENALTY_DELETED]: PRIORITIES.LOW,
  [EVENTS.PENALTY_WAIVED]: PRIORITIES.NORMAL,
  
  // File events
  [EVENTS.FILE_SHARED]: PRIORITIES.NORMAL,
  [EVENTS.FILE_UPLOADED]: PRIORITIES.NORMAL,
  [EVENTS.FILE_DOWNLOADED]: PRIORITIES.LOW,
  [EVENTS.FILE_DELETED]: PRIORITIES.LOW,
  
  // Drive/Storage events
  [EVENTS.DRIVE_FILE_SHARED]: PRIORITIES.NORMAL,
  [EVENTS.DRIVE_FOLDER_SHARED]: PRIORITIES.NORMAL,
  [EVENTS.DRIVE_PERMISSION_REVOKED]: PRIORITIES.HIGH,
  [EVENTS.DRIVE_FILE_UPLOADED]: PRIORITIES.LOW,
  [EVENTS.DRIVE_FOLDER_CREATED]: PRIORITIES.LOW,
  [EVENTS.DRIVE_FILE_DELETED]: PRIORITIES.NORMAL,
  [EVENTS.DRIVE_FOLDER_DELETED]: PRIORITIES.NORMAL,
  [EVENTS.DRIVE_COMMENT_ADDED]: PRIORITIES.NORMAL,
  
  // Resource events
  [EVENTS.RESOURCE_ADDED]: PRIORITIES.NORMAL,
  [EVENTS.RESOURCE_UPDATED]: PRIORITIES.LOW,
  [EVENTS.RESOURCE_DELETED]: PRIORITIES.LOW,
  [EVENTS.RESOURCE_SHARED]: PRIORITIES.NORMAL,
  
  // Enrollment events
  [EVENTS.ENROLLMENT_CONFIRMED]: PRIORITIES.NORMAL,
  [EVENTS.ENROLLMENT_PENDING]: PRIORITIES.NORMAL,
  [EVENTS.ENROLLMENT_APPROVED]: PRIORITIES.NORMAL,
  [EVENTS.ENROLLMENT_REJECTED]: PRIORITIES.HIGH,
  [EVENTS.ENROLLMENT_DROPPED]: PRIORITIES.NORMAL,
  [EVENTS.ENROLLMENT_COMPLETED]: PRIORITIES.NORMAL,
  
  // Grade events
  [EVENTS.GRADE_POSTED]: PRIORITIES.NORMAL,
  [EVENTS.GRADE_UPDATED]: PRIORITIES.NORMAL,
  [EVENTS.GRADE_CALCULATED]: PRIORITIES.NORMAL,
  [EVENTS.GRADE_FINAL]: PRIORITIES.HIGH,
  [EVENTS.MARKS_UPDATED]: PRIORITIES.NORMAL,
  [EVENTS.REPEATED_ATTEMPT_GRADED]: PRIORITIES.NORMAL,
  
  // Quiz events
  [EVENTS.QUIZ_AVAILABLE]: PRIORITIES.NORMAL,
  [EVENTS.QUIZ_STARTED]: PRIORITIES.LOW,
  [EVENTS.QUIZ_SUBMITTED]: PRIORITIES.NORMAL,
  [EVENTS.QUIZ_GRADED]: PRIORITIES.NORMAL,
  [EVENTS.QUIZ_TIME_WARNING]: PRIORITIES.HIGH,
  
  // Assignment events
  [EVENTS.ASSIGNMENT_CREATED]: PRIORITIES.NORMAL,
  [EVENTS.ASSIGNMENT_DUE]: PRIORITIES.HIGH,
  [EVENTS.ASSIGNMENT_DUE_SOON]: PRIORITIES.HIGH,
  [EVENTS.ASSIGNMENT_SUBMITTED]: PRIORITIES.NORMAL,
  [EVENTS.ASSIGNMENT_GRADED]: PRIORITIES.NORMAL,
  [EVENTS.ASSIGNMENT_OVERDUE]: PRIORITIES.URGENT,
  
  // Activity events
  [EVENTS.ACTIVITY_ASSIGNED]: PRIORITIES.NORMAL,
  [EVENTS.ACTIVITY_COMPLETED]: PRIORITIES.NORMAL,
  [EVENTS.ACTIVITY_GRADED]: PRIORITIES.NORMAL,
  [EVENTS.ACTIVITY_FEEDBACK]: PRIORITIES.NORMAL,
  
  // System events
  [EVENTS.SYSTEM_ALERT]: PRIORITIES.URGENT,
  [EVENTS.SYSTEM_MAINTENANCE]: PRIORITIES.HIGH,
  [EVENTS.SYSTEM_UPDATE]: PRIORITIES.NORMAL,
  [EVENTS.USER_ACCOUNT_CREATED]: PRIORITIES.NORMAL,
  [EVENTS.USER_PASSWORD_RESET]: PRIORITIES.NORMAL,
  [EVENTS.USER_LOGIN]: PRIORITIES.LOW
};

// Helper function to get category from event
export const getCategoryFromEvent = (event) => {
  return EVENT_CATEGORIES[event] || CATEGORIES.SYSTEM;
};

// Helper function to get default priority from event
export const getPriorityFromEvent = (event) => {
  return EVENT_PRIORITIES[event] || PRIORITIES.NORMAL;
};

export default {
  CATEGORIES,
  EVENTS,
  PRIORITIES,
  CHANNELS,
  DELIVERY_STATUS,
  EVENT_CATEGORIES,
  EVENT_PRIORITIES,
  getCategoryFromEvent,
  getPriorityFromEvent
};
