export default {
  index: 'Help Center',
  '-- Getting Started': { type: 'separator', title: 'Getting Started' },
  home: 'Home',
  dashboard: 'Dashboard',
  analytics: 'Analytics',
  '-- Academic': { type: 'separator', title: 'Academic' },
  quizzes: 'Quizzes',
  scheduling: 'Scheduling',
  '-- Operations': { type: 'separator', title: 'Operations' },
  attendance: 'Attendance',
  workflow: 'Workflow',
  '-- Communication': { type: 'separator', title: 'Communication' },
  chat: 'Chat',
  notifications: 'Notifications',
  '-- Files': { type: 'separator', title: 'Files' },
  'smart-drive': 'Smart Drive',
  '-- Account': { type: 'separator', title: 'Account' },
  profile: 'Profile & Settings',
  '-- Reference': { type: 'separator', title: 'Reference' },
  glossary: 'Glossary',
  shortcuts: 'Keyboard Shortcuts',
  faq: 'FAQ',
  changelog: "What's New",
}
